import React from "react";
import type { Metadata } from "next";
import "./global.css";

import Header from "./components/Header";
import About from "./components/About";
import Contact from "./components/Contact";
import History from "./components/History";
import Footer from "./components/Footer";
import Internship from "./components/Internship";

export const metadata: Metadata = {
  title: "Tony Nguyen Le",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
          <Header />
          <About />
          <Contact />
          <History />
          <Internship />
          <Footer />
          {children}
      </body>
    </html>
  );
}
