import React from "react";
import type { Metadata } from "next";
import "./global.css";

import Header from "./components/Header";
import About from "./components/About";
import Contact from "./components/Contact";
import History from "./components/History";
import Footer from "./components/Footer";
import Internship from "./components/Internship";
import Projects from "./components/Projects";
import Experience from "./components/Experience";

export const metadata: Metadata = {
  title: "Tony Nguyen Le",
  description: "Generated by create next app",
};

export default function RootLayout() {
  return (
    <html lang="en">
      <body>
        <Header />
        <About />
        <Contact />
        <History />
        <Internship />
        <Projects />
        <Experience />
        <Footer />
      </body>
    </html>
  );
}
